# Numpy & Maths basics

## Wprowadzenie do podstaw

### Wektory
O wektorach można myśleć na dwa sposoby:
- Fizycznie: Jako strzałki w przestrzeni, które mają określony kierunek i długość. Przykładem może być sytuacja, kiedy przechodzisz z punktu A do punktu B. Kierunek swojego ruchu oraz przebyta odległość mogą być reprezentowane przez wektor. Jeśli idziesz 5 metrów na wschód, możemy to opisać jako wektor wskazujący na wschód o długości 5 metrów. Na odwrót, pokonanie 5 metrów w kierunku zachodnim opisać można wektorem.

- Matematycznie: Jako ciąg liczb, które określają długość wektora w każdym z wymiarów przestrzeni. Na przykład, wektor (3, 4) w układzie współrzędnych oznacza, że rozpoczynając w punkcie (0,0) – środku układu współrzędnych – przesuwamy się o 3 jednostki w prawo (wzdłuż osi x) i 4 jednostki w górę (wzdłuż osi y). To tworzy wektor kończący się w punkcie (3, 4).

Choć najłatwiej jest wyobrażać sobie wektory w dwuwymiarowej przestrzeni (2D, jak strzałki na kartce) lub w trójwymiarowej (3D, strzałki w przestrzeni), możemy również rozważać wektory w przestrzeniach o dowolnej liczbie wymiarów, jak na przykład ciąg liczb.

UWAGA: długość i liczba wymiarów wektora to nie to samo! Np. wektor (3, 4) ma dwa wymiary, ale jego długość to $\sqrt{3^2 + 4^2} = 5$ z Twierdzenia Pitagorasa.

Wektory są kluczowe w matematyce i fizyce, ponieważ umożliwiają zrozumienie i obliczanie różnorodnych zjawisk w naukach przyrodniczych i technice. Aby pracować z wektorami w Pythonie, używamy biblioteki o nazwie numpy, która jest bardzo popularna wśród naukowców i inżynierów. Poniżej przedstawimy, jak możemy zdefiniować wektory i wykonać na nich proste operacje.

#### Dodawanie wektorów

Dodawanie wektorów jest równoznaczne z dodaniem ich odpowiednich składowych. Na przykład, suma wektorów a i b definiowana jest jako
$$ \begin{bmatrix}c_1 \\ c_2\end{bmatrix} = c = a + b = \begin{bmatrix}a_1  \\ a_2 \end{bmatrix} + \begin{bmatrix} b_1 \\  b_2\end{bmatrix}= \begin{bmatrix}a_1 + b_1 \\ a_2 + b_2\end{bmatrix}$$

#### Mnożenie wektora przez skalar

Mnożenie wektora przez liczbę polega na pomnożeniu każdej składowej wektora. Na przykład, jeśli chcemy pomnożyć wektor a przez 3, wynik będzie wyglądał następująco:
$$ \begin{bmatrix}c_1 \\ c_2\end{bmatrix} = c = 3 * a = 3 * \begin{bmatrix}a_1  \\ a_2 \end{bmatrix} = \begin{bmatrix}3 * a_1 \\ 3 * a_2\end{bmatrix}$$

#### Iloczyn skalarny (dot product)

Iloczyn skalarny dwóch wektorów a i b jest definiowany jako suma iloczynów ich odpowiednich składowych:
$$ a \cdot b = \begin{bmatrix}a_1  \\ a_2 \end{bmatrix} \cdot \begin{bmatrix} b_1 \\  b_2\end{bmatrix}= a_1 * b_1 + a_2 * b_2 $$


### Macierze

Macierze to dwuwymiarowe tablice liczb, które można postrzegać jako zbiór wektorów ułożonych w wiersze i kolumny. Macierze są używane do reprezentowania i rozwiązywania układów równań liniowych, transformacji geometrycznych oraz wielu innych zastosowań w matematyce i naukach przyrodniczych.

#### Mnożenie macierzy przez wektor

$$ A * v = \begin{bmatrix}a_1 & a_2 \\ a_3 & a_4\end{bmatrix} * \begin{bmatrix}v_1 \\ v_2\end{bmatrix}= \begin{bmatrix}a_1v_1 + a_2v_2  \\ a_3v_1 +  a_4v_2\end{bmatrix} $$

### Mnożenie macierzy przez macierz
$$ A * B = \begin{bmatrix}a_1 & a_2 \\ a_3 & a_4\end{bmatrix} * \begin{bmatrix}b_1 & b_2 \\ b_3 & b_4\end{bmatrix}= \begin{bmatrix}a_1b_1 + a_2b_3 & a_1b_2 + a_2b_4 \\ a_3b_1 + a_4b_3 & a_3b_2 + a_4b_4\end{bmatrix} $$

## Importowanie biblioteki numpy i wprowadzenie do tablic numpy

In [2]:
import numpy as np

NumPy jest podstawowym pakietem do obliczeń naukowych w Pythonie. Zapewnia wielowymiarowe tablice oraz zestaw zoptymalizowanych, szybkich operacji na tablicach, w tym matematycznych, logicznych, manipulacji kształtem, sortowania, wybierania, I/O, podstawowej algebry liniowej, operacji statystycznych, symulacji losowych i wielu innych.

Sercem pakietu NumPy jest obiekt ndarray. Reprezentuje on n-wymiarowe tablice jednorodnych typów danych, z wieloma operacjami wykonywanymi w skompilowanym kodzie dla wydajności. Istnieje kilka istotnych różnic między tablicami NumPy a standardowymi sekwencjami Pythona:
- Elementy w tablicy NumPy muszą być tego samego typu danych i tym samym rozmiaru w pamięci. Wyjątkiem są tablice obiektów Pythona (w tym NumPy), które pozwalają na tablice o elementach różnej wielkości.
- Tablice NumPy ułatwiają zaawansowane operacje matematyczne i inne na dużych ilościach danych. Takie operacje są zazwyczaj wykonywane bardziej efektywnie i z mniejszą ilością kodu niż przy użyciu wbudowanych funkcji Pythona.
- Coraz więcej naukowych i matematycznych pakietów opartych na Pythonie korzysta z tablic NumPy; choć zazwyczaj obsługują one wejście w postaci sekwencji Pythona, konwertują takie wejście na tablice NumPy przed przetwarzaniem, a często również zwracają tablice NumPy. Innymi słowy, aby efektywnie korzystać z większości dzisiejszego naukowego/matematycznego oprogramowania opartego na Pythonie, samo znajomość wbudowanych typów sekwencji Pythona nie wystarczy - trzeba również znać sposób korzystania z tablic NumPy.

## Tworzenie tablic numpy

In [11]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

array_2d = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
print("\n2D Array:")
print(array_2d)

array_3d = np.array(
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ]
)

print("\n3D Array:")
print(array_3d)

array_float = np.array([1, 2, 3], dtype=np.float32)
print("\nArray with Float Data Type:")
print(array_float)

print("\nConverted Array to Int Data Type:")
array_converted = array_float.astype(np.int32)
print(array_converted)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Array with Float Data Type:
[1. 2. 3.]

Converted Array to Int Data Type:
[1 2 3]


## Inne sposoby tworzenia tablic numpy

In [12]:
# Tworzenie tablicy wypełnionej zerami, jedynkami, określoną wartością, losowymi wartościami oraz macierzy jednostkowej
shape = (3, 4)

zeros_array = np.zeros(shape)
print("Array of Zeros:")
print(zeros_array)

ones_array = np.ones(shape)
print("\nArray of Ones:")
print(ones_array)

fill_value = 42
filled_array = np.full(shape, fill_value)
print("\nArray Filled with 42:")
print(filled_array)

random_array = np.random.random(shape)
print("\nArray with Random Values:")
print(random_array)

identity_matrix = np.eye(4)
print("\nIdentity Matrix:")
print(identity_matrix)

Array of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array of Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array Filled with 42:
[[42 42 42 42]
 [42 42 42 42]
 [42 42 42 42]]

Array with Random Values:
[[0.25942066 0.89361075 0.04792454 0.32096841]
 [0.25305884 0.32811647 0.10818942 0.89356587]
 [0.59539805 0.26827952 0.01547166 0.76472746]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Operacje na wektorach i macierzach

In [13]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

# Dodawanie wektorów
vector_sum = v + w
print("Vector Sum:")
print(vector_sum)

# Mnożenie wektora przez skalar
scalar = 3
scaled_vector = scalar * v
print("\nScaled Vector:")
print(scaled_vector)

# Iloczyn skalarny
dot_product = np.dot(v, w)
print("\nDot Product:")
print(dot_product)

Vector Sum:
[5 7 9]

Scaled Vector:
[3 6 9]

Dot Product:
32


In [14]:
A = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)
B = np.array(
    [
        [5, 6],
        [7, 8]
    ]
)

# Mnożenie macierzy przez wektor
vector = np.array([1, 2])
print("Matrix-Vector Multiplication:")
print(A @ vector)  # or np.dot(A, vector)

# WAŻNE: aby pomnożyć macierze i wektory korzystamu z operatora @ lub funkcji np.dot()
# W przeciwnym razie użycie operatora * spowoduje mnożenie elementów odpowiadających sobie pozycji
print("\nMatrix-Vector Multiplication using * operator (element-wise multiplication):")
print(A * vector)

# Mnożenie macierzy przez macierz
matrix_product = A @ B  # or np.dot(A, B)
print("\nMatrix-Matrix Multiplication:")
print(matrix_product)

Matrix-Vector Multiplication:
[ 5 11]

Matrix-Vector Multiplication using * operator (element-wise multiplication):
[[1 4]
 [3 8]]

Matrix-Matrix Multiplication:
[[19 22]
 [43 50]]


### Indeksowanie
Wiemy już jak tworzyć tablice numpy oraz wykonywać na nich podstawowe operacje matematyczne. Teraz przyjrzyjmy się jak wybierać elementy z tablic numpy i jak je modyfikować.


In [17]:
array = np.array(
    [
        [10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]
    ]
)
print("Original Array:")
print(array)

# wybieranie pojedyńczego elementu
element = array[1, 2]  # element w 2 wierszu i 3 kolumnie - indeksowanie zaczyna się od 0
print("\nSingle Element at (1, 2):")
print(element)

# wybieranie całego wiersza
row = array[0, :]  # pierwszy wiersz
print("\nFirst Row:")
print(row)
# wybieranie całej kolumny
column = array[:, 1]  # druga kolumna
print("\nSecond Column:")
print(column)


# modyfikacja elementu
array[2, 0] = 999  # zmiana elementu w 3 wierszu i 1 kolumnie
print("\nArray after Modifying Element at (2, 0):")
print(array)

# modyfikacja wybranych elementów
array[0, 1:3] = [111, 222]  # zmiana elementów w pierwszym wierszu, 2 i 3 kolumna
print("\nArray after Modifying Elements in First Row, Columns 1 and 2:")
print(array)

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Single Element at (1, 2):
60

First Row:
[10 20 30]

Second Column:
[20 50 80]

Array after Modifying Element at (2, 0):
[[ 10  20  30]
 [ 40  50  60]
 [999  80  90]]

Array after Modifying Elements in First Row, Columns 1 and 2:
[[ 10 111 222]
 [ 40  50  60]
 [999  80  90]]


### Modyfikowanie warunkowe tablic numpy

In [18]:
array = np.array([10, 15, 20, 25, 30, 35, 40])
print("Original Array:")
print(array)

# wybieranie elementów większych niż 25
condition = array > 25
filtered_array = array[condition]
print("\nElements Greater than 25:")
print(filtered_array)
# modyfikacja elementów większych niż 25
array[condition] = 999
print("\nArray after Modifying Elements Greater than 25:")
print(array)

Original Array:
[10 15 20 25 30 35 40]

Elements Greater than 25:
[30 35 40]

Array after Modifying Elements Greater than 25:
[ 10  15  20  25 999 999 999]
