In [1]:
import numpy as np

## 1) Tablica 100×100 z tabliczką mnożenia (od 0 do 99)
**Cel:** Utwórz tablicę 100×100, w której element `(i, j)` to iloczyn `i * j` dla `i, j` od 0 do 99.

In [2]:
# Rozwiązanie tutaj

wynik_1.shape, wynik_1[:5, :5]  # fragment wyniku do porównania

((100, 100),
 array([[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12],
        [ 0,  4,  8, 12, 16]]))

## 2) Pierwsze 100 liczb z pominięciem tych podzielnych przez 2, 3 lub 5
**Cel:** Weź liczby od 0 do 99 i usuń te, które dzielą się przez 2 **lub** 3 **lub** 5.

In [3]:
# Rozwiązanie tutaj

wynik_2.shape, wynik_2[:10]  # fragment wyniku do porównania

((26,), array([ 1,  7, 11, 13, 17, 19, 23, 29, 31, 37]))

## 3) Przycięcie do przedziału
**Cel:**
1. Wylicz `y = sin(x) + cos(x)` dla `x ∈ {0, 1, ..., 99}` w radianach.
2. Policz średnią wartość `y`.
3. Ogranicz wszystkie wartości do przedziału `[średnia - 0.1, średnia + 0.1]`.

In [4]:
# Rozwiązanie tutaj

wynik_3.shape, wynik_3[:5]  # fragment wyniku do porównania

((100,),
 array([ 0.09984587,  0.09984587,  0.09984587, -0.10015413, -0.10015413]))

## 4) Tablica 100×100 z jedynkami na obu przekątnych i na krawędziach
**Cel:** Zbuduj macierz 100×100, w której na obu przekątnych i na krawędziach są jedynki, a w pozostałych miejscach zera.

In [5]:
# Rozwiązanie tutaj

wynik_4.shape, wynik_4[:5, :5]  # fragment wyniku do porównania

((100, 100),
 array([[1, 1, 1, 1, 1],
        [1, 1, 0, 0, 0],
        [1, 0, 1, 0, 0],
        [1, 0, 0, 1, 0],
        [1, 0, 0, 0, 1]]))

## 5) 128. liczba Fibonacciego modulo $10^9+7$ przy użyciu potęgowania macierzy
**Cel:** Użyj odpowiedniej macierzy i szybkiego potęgowania, aby policzyć 128 liczbę Fibonacciego modulo 1e9 + 7.

In [6]:
# Rozwiązanie tutaj

wynik_5 % 1337  # wynik modulo 1337, aby nie dało się oszukać

372

# Zapisz wyniki do output.npz i wyślij je do sprawdzenia

In [7]:
# Zapisywanie wyników do wysłania (output.npy)
# (jeśli nie masz któregoś, po prostu ustaw wynik_X = 0)
np.savez(
    "output.npz",
    wynik_1=wynik_1,
    wynik_2=wynik_2,
    wynik_3=wynik_3,
    wynik_4=wynik_4,
    wynik_5=wynik_5
)